version: "3.9"
services:
  backend:
    build: ./backend
    image: ${BACKEND_IMAGE:-whiterabbit-backend:latest}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - model-data:/app/model
      - ./backend/pretrained:/app/pretrained
    networks:
      - app-network

  frontend:
    build: ./frontend
    image: ${FRONTEND_IMAGE:-whiterabbit-frontend:latest}
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  model-data: