services:
  # Backend service
  - type: web
    name: rl-project-backend
    runtime: docker
    repo: https://github.com/gordonkoehn/whiteRabbit.git # Replace with your actual GitHub username
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend  # Set context to the backend directory
    healthCheckPath: /docs # Updated health check endpoint
    envVars:
      - key: VENICE_API_KEY
        sync: false # Requires manual setting in Render dashboard
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  # Frontend service
  - type: web
    name: rl-project-frontend
    runtime: docker
    repo: https://github.com/gordonkoehn/whiteRabbit.git # Replace with your actual GitHub username
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend  # Set context to the frontend directory
    healthCheckPath: /
    envVars:
      - key: BACKEND_URL
        value: https://rl-project-backend.onrender.com # This URL will be your Render backend URL
    dockerCommand: streamlit run app/main.py --server.port $PORT --server.address 0.0.0.0