name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          pytest backend/tests/
      - name: Install frontend dependencies
        run: |
          pip install -r frontend/requirements.txt
      - name: Build Docker images
        run: |
          docker-compose build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker tag rl-project_backend:latest yourusername/rl-backend:latest
          docker tag rl-project_frontend:latest yourusername/rl-frontend:latest
          docker push yourusername/rl-backend:latest
          docker push yourusername/rl-frontend:latest
      - name: Deploy backend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_BACKEND_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"image_url":"yourusername/rl-backend:latest"}' \
            https://api.render.com/v1/services/$RENDER_BACKEND_SERVICE_ID/deploys
      - name: Deploy frontend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_FRONTEND_SERVICE_ID: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"image_url":"yourusername/rl-frontend:latest"}' \
            https://api.render.com/v1/services/$RENDER_FRONTEND_SERVICE_ID/deploys