name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install backend dependencies
        run: |
          pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          pytest backend/tests/
      - name: Install frontend dependencies
        run: |
          pip install -r frontend/requirements.txt
      - name: Build Docker images
        run: |
          docker-compose build